# Generated by Django 5.0.1 on 2026-02-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Is this a paid blog post?'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in rupees', max_digits=10),
        ),
    ]
